<a href="https://colab.research.google.com/github/chithrakumardakshan-cloud/northstar-analytics/blob/main/notebooks/01_sql_in_r.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ==========================================
# NORTHSTAR URBAN MOBILITY ANALYTICS
# SQL IN R ANALYSIS
# ==========================================

# STEP 1 — INSTALL AND LOAD PACKAGES

install.packages("sqldf")
install.packages("dplyr")
install.packages("ggplot2")

library(sqldf)
library(dplyr)
library(ggplot2)

cat("Libraries loaded successfully.")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Libraries loaded successfully.

In [2]:
# STEP 2 — LOAD DATASETS

orders <- read.csv("orders.csv")
deliveries <- read.csv("deliveries.csv")
customers <- read.csv("customers.csv")
drivers <- read.csv("drivers.csv")
vehicles <- read.csv("vehicles.csv")
hubs <- read.csv("hubs.csv")
incidents <- read.csv("incidents.csv")
complaints <- read.csv("complaints.csv")
app_events <- read.csv("app_events.csv")

cat("Datasets loaded successfully.")

Datasets loaded successfully.

In [3]:
# STEP 3 — PREVIEW DATA

head(orders)

head(deliveries)

str(orders)

str(deliveries)

  order_id customer_id service_type order_created_at    promised_window_hours
1 O00001   C0292       Passenger    2024-08-20 14:43:00  6
2 O00002   C0459       Passenger    2024-05-14 22:16:00 24
3 O00003   C0161       Passenger    2025-09-02 14:37:00  4
4 O00004   C0520       Parcel       2025-01-11 17:15:00  2
5 O00005   C0558       Retail       2025-02-17 19:32:00 12
6 O00006   C0437       Retail       2024-08-05 04:55:00  1
  pickup_zone dropoff_zone priority_level order_value booking_channel
1 Airport     South        Medium         126.65      App
2 North       AIRPORT      Low            109.30      App
3 West        AIRPORT      High            33.50      Phone
4 RiverSide   North        Medium          10.04      App
5 Riverside   SOUTH        Low            125.58      Phone
6 CENTRAL     East         High           151.44      Web
  special_handling_flag
1 0
2 0
3 0
4 1
5 0
6 1

  delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1 DL00001     O00938   D004      V056       H05    2024-06-18 10:57:00
2 DL00002     O00004   D138      V007       H02    2025-01-11 18:45:00
3 DL00003     O00639   D006      V049       H02    2025-06-02 20:39:00
4 DL00004     O00313   D116      V055       H02    2024-03-08 23:31:00
5 DL00005     O00844   D108      V034       H01    2025-09-21 11:43:00
6 DL00006     O00029   D037      V098       H03    2024-09-11 12:40:00
  delivery_completed_at      delivery_status route_distance_km
1 2024-06-19 09:05:59.904311 Failed          17.26
2 2025-01-11 17:39:00.000000 OnTime          10.34
3 2025-06-02 21:45:32.366770 OnTime           7.92
4 2024-03-09 23:30:08.103702 Delayed         16.42
5 2025-09-21 15:45:34.131056 OnTime          14.52
6 2024-09-12 17:11:52.384869 Delayed         13.84
  manual_route_override_count proof_of_completion_missing
1 1                           0
2 1                           0
3 0                           0
4 0                           0
5 1                           0
6 0                           0
  customer_rating_post_delivery fuel_or_charge_cost
1 3.07                          12.05
2 5.00                          13.41
3 4.98                           8.51
4 4.18                          13.62
5 4.18                           9.22
6 1.57                           9.58

'data.frame':	1250 obs. of  11 variables:
 $ order_id             : chr  "O00001" "O00002" "O00003" "O00004" ...
 $ customer_id          : chr  "C0292" "C0459" "C0161" "C0520" ...
 $ service_type         : chr  "Passenger" "Passenger" "Passenger" "Parcel" ...
 $ order_created_at     : chr  "2024-08-20 14:43:00" "2024-05-14 22:16:00" "2025-09-02 14:37:00" "2025-01-11 17:15:00" ...
 $ promised_window_hours: int  6 24 4 2 12 1 2 4 12 6 ...
 $ pickup_zone          : chr  "Airport" "North" "West" "RiverSide" ...
 $ dropoff_zone         : chr  "South" "AIRPORT" "AIRPORT" "North" ...
 $ priority_level       : chr  "Medium" "Low" "High" "Medium" ...
 $ order_value          : num  126.7 109.3 33.5 10 125.6 ...
 $ booking_channel      : chr  "App" "App" "Phone" "App" ...
 $ special_handling_flag: int  0 0 0 1 0 1 0 0 0 0 ...
'data.frame':	950 obs. of  13 variables:
 $ delivery_id                  : chr  "DL00001" "DL00002" "DL00003" "DL00004" ...
 $ order_id                     : chr  "O00938" "O00004" "O00639" "O00313" ...
 $ driver_id                    : chr  "D004" "D138" "D006" "D116" ...
 $ vehicle_id                   : chr  "V056" "V007" "V049" "V055" ...
 $ hub_id                       : chr  "H05" "H02" "H02" "H02" ...
 $ dispatch_time                : chr  "2024-06-18 10:57:00" "2025-01-11 18:45:00" "2025-06-02 20:39:00" "2024-03-08 23:31:00" ...
 $ delivery_completed_at        : chr  "2024-06-19 09:05:59.904311" "2025-01-11 17:39:00.000000" "2025-06-02 21:45:32.366770" "2024-03-09 23:30:08.103702" ...
 $ delivery_status              : chr  "Failed" "OnTime" "OnTime" "Delayed" ...
 $ route_distance_km            : num  17.26 10.34 7.92 16.42 14.52 ...
 $ manual_route_override_count  : int  1 1 0 0 1 0 0 1 1 1 ...
 $ proof_of_completion_missing  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ customer_rating_post_delivery: num  3.07 5 4.98 4.18 4.18 1.57 4.64 3.76 3.7 3.2 ...
 $ fuel_or_charge_cost          : num  12.05 13.41 8.51 13.62 9.22 ...

In [4]:
# QUERY 1 — DELIVERY FAILURE RATE BY HUB

query1 <- sqldf("
SELECT
    h.hub_name,
    h.zone,
    COUNT(d.delivery_id) AS total_deliveries,

    SUM(
        CASE
            WHEN d.delivery_status = 'Failed'
            THEN 1
            ELSE 0
        END
    ) AS failed_deliveries,

    ROUND(
        SUM(
            CASE
                WHEN d.delivery_status = 'Failed'
                THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(d.delivery_id),
        2
    ) AS failure_rate

FROM deliveries d

JOIN hubs h
ON d.hub_id = h.hub_id

GROUP BY h.hub_name, h.zone

ORDER BY failure_rate DESC
")

query1

  hub_name       zone      total_deliveries failed_deliveries failure_rate
1 Midtown Relay  Central   128              26                20.31
2 Central Core   Central   115              23                20.00
3 Airport Hub    Airport   104              15                14.42
4 West Gate      West      127              16                12.60
5 North Exchange North     136              17                12.50
6 Riverside Hub  Riverside 115              14                12.17
7 South Link     South     106              10                 9.43
8 East Dock      East      119              11                 9.24

In [5]:
# QUERY 2 — DRIVER PERFORMANCE ANALYSIS

query2 <- sqldf("
SELECT
    d.driver_id,
    dr.base_zone,
    dr.employment_type,

    COUNT(d.delivery_id) AS total_deliveries,

    ROUND(
        AVG(d.manual_route_override_count),
        2
    ) AS avg_overrides,

    ROUND(
        AVG(d.customer_rating_post_delivery),
        2
    ) AS avg_customer_rating

FROM deliveries d

JOIN drivers dr
ON d.driver_id = dr.driver_id

GROUP BY
    d.driver_id,
    dr.base_zone,
    dr.employment_type

HAVING total_deliveries >= 3

ORDER BY avg_overrides DESC
")

query2

    driver_id base_zone employment_type total_deliveries avg_overrides
1   D127      CENTRAL   FullTime         6               2.83
2   D062      South     FullTime         3               2.00
3   D069      NORTH     PartTime         7               2.00
4   D085      North     PartTime         4               2.00
5   D105      RiverSide Contract         7               2.00
6   D124      north     FullTime         4               2.00
7   D130      WEST      FullTime         8               2.00
8   D139      South     FullTime         5               2.00
9   D028      North     FullTime         7               1.86
10  D027      AIRPORT   PartTime         6               1.83
11  D143      CENTRAL   FullTime         5               1.80
12  D003      AIRPORT   FullTime         4               1.75
13  D107      RiverSide FullTime         4               1.75
14  D136      Airport   FullTime         4               1.75
15  D104      WEST      FullTime         7               1.71
16  D042      North     FullTime         3               1.67
17  D090      NORTH     FullTime         6               1.67
18  D114      Ctr       FullTime         3               1.67
19  D131      SOUTH     FullTime         9               1.67
20  D073      East      FullTime         5               1.60
21  D033      South     PartTime         7               1.57
22  D008      SOUTH     FullTime         8               1.50
23  D103      Central   FullTime         4               1.50
24  D030      CENTRAL   FullTime         7               1.43
25  D098      SOUTH     Contract         5               1.40
26  D108      South     FullTime        11               1.36
27  D046      South     FullTime         6               1.33
28  D074      Central   FullTime         6               1.33
29  D087      north     Contract        12               1.33
30  D122      South     FullTime         3               1.33
⋮   ⋮         ⋮         ⋮               ⋮                ⋮
122 D097      West      FullTime         7               0.43
123 D116      CENTRAL   FullTime         7               0.43
124 D123      RiverSide FullTime         7               0.43
125 D049      CENTRAL   Contract        10               0.40
126 D092      East      FullTime         5               0.40
127 D101      WEST      FullTime         5               0.40
128 D156      South     FullTime         5               0.40
129 D157      South     FullTime         5               0.40
130 D037      north     PartTime         8               0.38
131 D102      East      PartTime        13               0.38
132 D164      Central   FullTime         8               0.38
133 D015      East      FullTime         6               0.33
134 D023      EAST      FullTime         6               0.33
135 D034      West      FullTime         6               0.33
136 D045      NORTH     FullTime         9               0.33
137 D063      north     PartTime         3               0.33
138 D093      South     PartTime         6               0.33
139 D140      North     FullTime         3               0.33
140 D018      WEST      PartTime         7               0.29
141 D155      CENTRAL   PartTime         7               0.29
142 D014      NORTH     FullTime         4               0.25
143 D058      AIRPORT   FullTime         4               0.25
144 D061      RiverSide Contract         4               0.25
145 D064      SOUTH     PartTime         4               0.25
146 D128      Central   Contract         4               0.25
147 D167      SOUTH     PartTime         4               0.25
148 D091      Riverside FullTime         6               0.17
149 D071      CENTRAL   PartTime         7               0.14
150 D025      North     FullTime         3               0.00
151 D109      Central   Contract         4               0.00
    avg_customer_rating
1   4.10
2   3.82
3   3.94
4   3.42
5   4.21
6   3.41
7   3.80
8   4.08
9   3.54
10  3.64
11  3.76
12  4.45
13  4.13
14  3.67
15  3.93
16  4.01
17  4.01
18  4.25
19  3.66
20  4.02
21  3.95
22  3.92
23  3.28
24  4.31
25  3.59
26  4.41
27  4.13
28  3.73
29  3.82
30  4.72
⋮   ⋮
122 3.71
123 3.65
124 3.65
125 3.76
126 3.38
127 3.56
128 3.55
129 4.16
130 4.07
131 4.14
132 4.34
133 4.52
134 3.90
135 3.88
136 4.25
137 2.37
138 4.22
139 3.40
140 3.92
141 4.20
142 4.43
143 4.06
144 4.61
145 4.23
146 3.85
147 4.35
148 3.13
149 3.95
150 4.65
151 3.52

In [6]:
# QUERY 3 — CUSTOMER COMPLAINT ANALYSIS

query3 <- sqldf("
SELECT
    c.customer_id,
    c.home_zone,
    c.customer_type,

    COUNT(cp.complaint_id) AS total_complaints,

    SUM(
        CASE
            WHEN d.delivery_status = 'Failed'
            THEN 1
            ELSE 0
        END
    ) AS failed_deliveries,

    ROUND(
        SUM(cp.compensation_amount),
        2
    ) AS total_compensation

FROM customers c

LEFT JOIN complaints cp
ON c.customer_id = cp.customer_id

LEFT JOIN orders o
ON c.customer_id = o.customer_id

LEFT JOIN deliveries d
ON o.order_id = d.order_id

GROUP BY
    c.customer_id,
    c.home_zone,
    c.customer_type

HAVING total_complaints >= 2

ORDER BY total_complaints DESC
")

query3

    customer_id home_zone customer_type total_complaints failed_deliveries
1   C0372       West      Consumer      18               3
2   C0545       SOUTH     Consumer      18               0
3   C0242       East      Consumer      15               0
4   C0023       South     Consumer      12               2
5   C0172       north     Consumer      12               0
6   C0335       NORTH     SME           12               0
7   C0368       North     Consumer      12               4
8   C0599       North     Consumer      12               0
9   C0622       RiverSide Consumer      12               0
10  C0032       West      Consumer      10               2
11  C0361       SOUTH     Consumer      10               0
12  C0476       NORTH     Consumer      10               2
13  C0529       Riverside SME           10               2
14  C0110       EAST      Consumer       9               3
15  C0421       CENTRAL   Consumer       9               0
16  C0573       AIRPORT   SME            9               3
17  C0626       SOUTH     Consumer       9               0
18  C0015       SOUTH     SME            8               0
19  C0054       WEST      Consumer       8               2
20  C0157       CENTRAL   Consumer       8               0
21  C0259       Central   Consumer       8               0
22  C0351       CENTRAL   Enterprise     8               2
23  C0369       West      Consumer       8               0
24  C0378       RiverSide Consumer       8               0
25  C0480       NORTH     Enterprise     8               2
26  C0564       EAST      Consumer       8               0
27  C0571       South     Consumer       8               0
28  C0595       CENTRAL   Consumer       8               0
29  C0597       north     Consumer       8               2
30  C0618       Airport   Consumer       8               2
⋮   ⋮           ⋮         ⋮             ⋮                ⋮
168 C0362       Ctr       Consumer      2                0
169 C0371       East      Consumer      2                1
170 C0381       Ctr       Consumer      2                0
171 C0384       Riverside Consumer      2                1
172 C0391       West      Consumer      2                1
173 C0393       East      Consumer      2                0
174 C0426       RiverSide SME           2                0
175 C0428       Riverside SME           2                0
176 C0444       Ctr       Consumer      2                0
177 C0445       Riverside SME           2                0
178 C0449       EAST      Enterprise    2                0
179 C0452       SOUTH     Consumer      2                1
180 C0454       South     Consumer      2                0
181 C0459       WEST      Consumer      2                0
182 C0464       AIRPORT   Enterprise    2                0
183 C0469       north     Consumer      2                0
184 C0475       CENTRAL   Consumer      2                0
185 C0491       Ctr       Consumer      2                0
186 C0495       Ctr       Consumer      2                0
187 C0509       WEST      Consumer      2                0
188 C0510       West      Consumer      2                0
189 C0515       Riverside Consumer      2                0
190 C0532       SOUTH     Consumer      2                0
191 C0544       north     Consumer      2                0
192 C0562       WEST      Consumer      2                0
193 C0566       CENTRAL   Consumer      2                0
194 C0586       CENTRAL   Consumer      2                0
195 C0610       South     Consumer      2                0
196 C0628       North     Consumer      2                1
197 C0639       East      Consumer      2                0
    total_compensation
1   431.34
2   441.60
3   378.75
4   265.44
5   245.96
6   277.32
7   232.53
8    52.44
9   109.14
10  135.30
11  299.85
12  147.50
13  186.40
14  132.42
15  356.94
16  334.26
17  108.69
18   77.84
19   49.64
20   63.08
21   83.00
22  408.08
23  141.84
24   65.08
25  155.04
26  151.72
27   47.44
28   99.20
29  208.44
30  201.28
⋮   ⋮
168 67.60
169 66.54
170 21.06
171 63.94
172 27.10
173 45.00
174 21.88
175  0.00
176 92.34
177 74.30
178 56.00
179  2.90
180 25.94
181 41.50
182 47.98
183 52.82
184    NA
185 58.50
186 40.36
187 32.34
188 70.79
189 40.08
190 51.12
191 77.80
192 38.96
193 94.18
194  6.32
195 43.64
196 60.80
197 40.12

In [7]:
# QUERY 4 — VEHICLE BATTERY HEALTH ANALYSIS

query4 <- sqldf("
SELECT

    CASE
        WHEN v.battery_health_pct >= 80
        THEN 'Excellent'

        WHEN v.battery_health_pct >= 60
        THEN 'Moderate'

        ELSE 'Poor'
    END AS battery_category,

    COUNT(DISTINCT v.vehicle_id) AS total_vehicles,

    COUNT(i.incident_id) AS incident_count,

    ROUND(
        AVG(i.resolved_hours),
        2
    ) AS avg_resolution_time

FROM vehicles v

JOIN deliveries d
ON v.vehicle_id = d.vehicle_id

LEFT JOIN incidents i
ON d.delivery_id = i.delivery_id

GROUP BY battery_category
")

query4

  battery_category total_vehicles incident_count avg_resolution_time
1 Excellent        47             115            11.41
2 Moderate         56             121            12.82
3 Poor             17              44            11.31

In [8]:
# QUERY 5 — SERVICE PROFITABILITY ANALYSIS

query5 <- sqldf("
SELECT
    o.pickup_zone,
    o.service_type,

    COUNT(o.order_id) AS total_orders,

    ROUND(
        AVG(o.order_value),
        2
    ) AS avg_order_value,

    ROUND(
        AVG(d.fuel_or_charge_cost),
        2
    ) AS avg_delivery_cost,

    ROUND(
        AVG(o.order_value - d.fuel_or_charge_cost),
        2
    ) AS avg_profit_margin

FROM orders o

JOIN deliveries d
ON o.order_id = d.order_id

GROUP BY
    o.pickup_zone,
    o.service_type

ORDER BY avg_profit_margin ASC
")

query5

   pickup_zone service_type total_orders avg_order_value avg_delivery_cost
1  West        Business      7           53.95           13.15
2  East        Medical       9           52.86           11.89
3  Ctr         Medical       2           53.92           11.13
4  north       Medical       7           57.49           14.17
5  AIRPORT     Business      5           66.61           18.22
6  Central     Passenger    20           61.75           11.90
7  RiverSide   Parcel       17           68.07           13.28
8  North       Parcel        8           67.15           10.84
9  East        Retail       20           69.57           11.73
10 West        Retail        8           70.02           10.40
11 EAST        Business      7           73.71           12.96
12 RiverSide   Passenger    19           73.98           13.17
13 WEST        Retail       14           74.22           11.62
14 Central     Parcel       11           74.99           12.30
15 South       Retail       16           76.36           13.23
16 SOUTH       Business      7           75.35           12.03
17 West        Medical       9           74.94           11.55
18 Central     Retail       14           76.84           12.36
19 Ctr         Retail       22           78.55           13.28
20 EAST        Parcel       23           80.31           14.15
21 NORTH       Medical       4           78.31           11.98
22 Riverside   Parcel       11           77.31           10.29
23 Central     Business      6           78.13           11.05
24 North       Business      8           79.45           11.89
25 north       Parcel        8           81.72           12.37
26 EAST        Retail       14           82.07           12.50
27 Central     Medical       4           83.62           13.77
28 NORTH       Parcel       11           85.64           13.85
29 WEST        Parcel       16           84.39           12.43
30 South       Business     12           85.98           13.63
⋮  ⋮           ⋮            ⋮            ⋮               ⋮
51 West        Passenger    12            96.99          12.27
52 SOUTH       Passenger    12            98.33          12.48
53 North       Retail        7            99.44          13.32
54 SOUTH       Medical      10            98.30          12.16
55 Ctr         Parcel       15            97.96          11.62
56 CENTRAL     Medical       7            99.11          12.75
57 Riverside   Passenger    14            98.98          11.02
58 South       Parcel       20           101.37          12.78
59 RiverSide   Medical      10           103.75          14.41
60 RiverSide   Business      7           102.83          13.29
61 NORTH       Business      3            97.88           8.20
62 AIRPORT     Medical       3           106.55          15.88
63 North       Passenger     7           107.16          15.33
64 Airport     Parcel       20           108.66          16.25
65 Riverside   Medical       4           102.39           9.40
66 RiverSide   Retail       13           105.48          12.15
67 SOUTH       Retail       15           104.75          11.18
68 East        Parcel       17           107.20          12.46
69 West        Parcel       15           108.85          12.76
70 WEST        Passenger    20           107.64          11.37
71 Airport     Passenger    18           113.89          15.83
72 East        Passenger    21           110.58          11.73
73 Riverside   Business     10           111.83          12.14
74 East        Business     11           113.16          13.32
75 north       Business     12           116.92          13.92
76 AIRPORT     Passenger    12           120.83          16.54
77 EAST        Passenger    24           119.00          11.85
78 north       Retail        9           122.53          14.72
79 Ctr         Business     12           122.10          12.02
80 CENTRAL     Business      6           152.78           9.40
   avg_profit_margin
1  40.81
2  40.97
3  42.79
4  43.32
5  48.39
6  49.85
7  54.80
8  56.31
9  57.84
10 59.62
11 60.75
12 60.81
13 62.61
14 62.68
15 63.14
16 63.32
17 63.39
18 64.47
19 65.27
20 66.15
21 66.33
22 67.02
23 67.08
24 67.55
25 69.35
26 69.58
27 69.84
28 71.79
29 71.97
30 72.36
⋮  ⋮
51  84.72
52  85.85
53  86.12
54  86.14
55  86.34
56  86.37
57  87.96
58  88.59
59  89.34
60  89.54
61  89.68
62  90.67
63  91.83
64  92.41
65  92.99
66  93.33
67  93.57
68  94.74
69  96.09
70  96.27
71  98.07
72  98.85
73  99.69
74  99.84
75 103.00
76 104.29
77 107.15
78 107.82
79 110.08
80 143.38

In [9]:
# STEP 4 — QUERY OPTIMISATION

# BEFORE OPTIMISATION

slow_query <- sqldf("
SELECT *
FROM deliveries d

JOIN orders o
ON d.order_id = o.order_id

WHERE d.delivery_status = 'Failed'
")

# AFTER OPTIMISATION

failed_deliveries <- deliveries[
    deliveries$delivery_status == 'Failed',
]

fast_query <- sqldf("
SELECT *
FROM failed_deliveries f

JOIN orders o
ON f.order_id = o.order_id
")

cat("Original delivery rows:", nrow(deliveries), "\n")

cat("Filtered failed rows:", nrow(failed_deliveries), "\n")

Original delivery rows: 950
Filtered failed rows: 132